# Generated by Django 5.1 on 2024-08-31 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('numberOfChips', models.CharField(max_length=100)),
                ('turn', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='api.card')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPlayers', models.CharField(max_length=100)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.player')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet', models.CharField(max_length=100)),
                ('hit', models.BooleanField(null=True)),
                ('stand', models.BooleanField(null=True)),
                ('double', models.BooleanField(null=True)),
                ('split', models.BooleanField(null=True)),
                ('bust', models.BooleanField(null=True)),
                ('win', models.BooleanField(null=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.deck')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='api.table')),
            ],
        ),
    ]
